from enum import Enum

class BookType(Enum):
    ADVENTURE = "Adventure"
    CLASSIC = "Classic"
    DYSTOPIAN = "Dystopian"
    EPIC_POETRY = "Epic Poetry"
    FANTASY = "Fantasy"
    FICTION = "Fiction"
    GOTHIC_FICTION = "Gothic Fiction"
    GOTHIC_ROMANCE = "Gothic Romance"
    HISTORICAL_FICTION = "Historical Fiction"
    MODERNISM = "Modernism"
    PHILOSOPHY = "Philosophy"
    PSYCHOLOGICAL_DRAMA = "Psychological Drama"
    REALISM = "Realism"
    ROMANCE = "Romance"
    SATIRE = "Satire"
    SCIENCE_FICTION = "Science Fiction"
    TRAGEDY = "Tragedy"